### PR TITLE
ADD Copy Button for Code & FIX Bugs (yonghwan / 241129)

### PR DESCRIPTION
**Pull request by NewPlus**
# ADD
## AI Part
- X
## Web Part
- Copy & Paste Button for Code Snippets
- Some Designs for the Button
# FIX
- **Bug 01**: The AI message was repeating itself in the chat card. -> FIX: Now there's only one response.

### CODE REVIEW

**Comment by NewPlus** [comment]
# Reviews(Fast)
- Got it.

**Comment by chogamy** [comment]
can you make vscode extension by "continue"? (https://github.com/continuedev/continue)
i prefer autocomplete function than chat-bot version
and also, GROQ supports free gpt serving. (https://console.groq.com/playground)

**Comment by NewPlus** [comment]
> can you make vscode extension by "continue"? (https://github.com/continuedev/continue) i prefer autocomplete function than chat-bot version and also, GROQ supports free gpt serving. (https://console.groq.com/playground)

Thank you for ur comment! :) This project is for my company. This is the first thing.
**1. make vscode extension by "continue" for autocomplete function**
- Yes. I want it(autocomplete func) too. But my company(this project is for here) is using Visual Studio and they don't want to develop in VS code because of security and license.
- But I think if I make an autocomplete ver with Visual Studio Extension, then maybe they love it. I'll find and work it!
**2. GROQ supports free gpt serving**
- I didn't know GROQ. I will check it! Thx a lot! :D
- But if it is for using only GPT or Claude(closed models with internet), then I can't use it because of security(my company really hate the cloud and internet connected system).

**Comment by chogamy** [comment]
Thank you for reply❤️❤️

**Pull request merged**
